name: 'CICD FOR CPET'

on:
  push:
    branches: [ "master" ]

jobs: 
  test:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: test site
        run: |
          npm install
        env: 
          CI: true

  deploy:
    timeout-minutes: 10
    needs: [test]
    runs-on: ubuntu-latest

    steps: 
      - name: connect to SSH
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.HOST}}     
            username: ${{secrets.USER}}  
            key: ${{secrets.SSH_KEY}}
            port: ${{secrets.PORT}}
            script: |
                whoami
                cd  ./CPET
                git pull origin master
                npm install --force
                # sudo rm -rf /var/www/cpet.dhiu.in/html/*
                # sudo cp -r /home/ubuntu/CPET/client/build/* /var/www/cpet.dhiu.in/html
                pm2 reload server.js
                sudo nginx -t
                sudo systemctl restart nginx
                sudo systemctl reload nginx

